import React from 'react'

const TermsPage = (props) => {
    return (

        <div className="container">

            <div className="container__centertext">
                <h1>Terms of Service</h1>
                <button onClick={props.toggle} className="link-button-dark">Back</button>
            </div>

            <h3>DEFINITIONS</h3>
            <p><strong>Company</strong> - Idea Fusion, Inc.</p>
            <p><strong>Services</strong> -  Idea Fusion, Inc. provides software for consumers and professionals to more efficiently and effectively complete their work, such as filling out forms. “Services” are defined as any functionality made available through Idea Fusion’s software, processes or other services, including but not limited to any functionality within the automatic form filling software product, Fetch.</p>
            <p><strong>Customer</strong> - Any person or entity that has logged in to or used any of the Company’s Services, thereby accepting these Terms of Service.</p>
            <p><strong>Term</strong> - Timeframe during which Customer has used Services, regardless if via a paid plan or not. On a monthly basis.</p>
            <p><strong>Initial Service Term</strong> - The first Term a customer has using Services.</p>

            <h3>TERMS AND CONDITIONS</h3>

            <h4>SERVICES AND SUPPORT</h4>
            <p>Subject to the terms of this Agreement, Company will use commercially reasonable efforts to provide Customer the Services. Customer is responsible for any and all activities that occur under their account. Customer agrees to notify Company immediately of any unauthorized use of accounts or any other breach of security. Company shall not be liable for any loss that Customer may incur as a result of someone else using their passwords or accounts, either with or without the applicable users' knowledge. Company reserves the right to refuse registration of accounts, or cancel passwords it deems inappropriate.</p>

            <h4>RESTRICTIONS AND RESPONSIBILITIES</h4>
            <p>Customer will not, directly or indirectly: reverse engineer, decompile, disassemble or otherwise attempt to discover the source code, object code or underlying structure, ideas, know-how or algorithms relevant to the Services or any software, documentation or data related to the Services (“Software”); modify, translate, or create derivative works based on the Services or any Software; use the Services or any Software for timesharing or service bureau purposes or otherwise for the benefit of a third; or remove any proprietary notices or labels.  With respect to any Software that is distributed or provided to Customer for use on Customer premises or devices, Company hereby grants Customer a non-exclusive, non-transferable, non-sublicensable license to use such Software during the Term only in connection with the Services. Further, Customer may not remove or export from the United States or allow the export or re-export of the Services, Software or anything related thereto, or any direct product thereof in violation of any restrictions, laws or regulations of the United States Department of Commerce, the United States Department of Treasury Office of Foreign Assets Control, or any other United States or foreign agency or authority.  As defined in FAR section 2.101, the Software and documentation are “commercial items” and according to DFAR section 252.2277014(a)(1) and (5) are deemed to be “commercial computer software” and “commercial computer software documentation.”  Consistent with DFAR section 227.7202 and FAR section 12.212, any use modification, reproduction, release, performance, display, or disclosure of such commercial software or commercial software documentation by the U.S. Government will be governed solely by the terms of this Agreement and will be prohibited except to the extent expressly permitted by the terms of this Agreement.</p>
            <p>Customer represents, covenants, and warrants that Customer will use the Services only in compliance with Company’s standard published use cases and all applicable laws and regulations. Customer hereby agrees to indemnify and hold harmless Company against any damages, losses, liabilities, settlements and expenses (including without limitation costs and attorneys’ fees) in connection with any claim or action that arises from an alleged violation of the foregoing or otherwise from Customer’s use of Services. Although Company has no obligation to monitor Customer’s use of the Services, Company may do so and may prohibit any use of the Services it believes may be (or alleged to be) in violation of the foregoing.</p>
            <p>Customer shall be responsible for obtaining and maintaining any equipment and ancillary services needed to connect to, access or otherwise use the Services, including, without limitation, modems, hardware, servers, software, operating systems, networking, web servers and the like (collectively, “Equipment”).  Customer shall also be responsible for maintaining the security of the Equipment, Customer account, passwords and files, and for all uses of Customer account or the Equipment with or without Customer’s knowledge or consent.</p>

            <h4>CONFIDENTIALITY; PROPRIETARY RIGHTS</h4>
            <p>Customer understands that Company has disclosed or may disclose business, technical or financial information relating to Company's business (hereinafter referred to as “Proprietary Information” of the Company).  Proprietary Information of Company includes non-public information regarding pricing, features, functionality and performance of the Service. Customer agrees: (i) to take reasonable precautions to protect such Proprietary Information, and (ii) not to use (except in performance of the Services or as otherwise permitted herein) or divulge to any third person any such Proprietary Information.</p>
            <p>Company shall own and retain all right, title and interest in and to (a) the Services and Software, all improvements, enhancements or modifications thereto, (b) any software, applications, inventions or other technology developed in connection with Implementation Services or support, any data that is entered by, uploaded by, based on or derived from the Customer and provided to Customer as part of the Services and (d) all intellectual property rights related to any of the foregoing. By accessing and/or using Services, users agree to report to Company all claims or suspected claims of copyright or other infringement of Company's intellectual property or other proprietary rights. Claims or suspected claims of infringement shall be reported to Company within one business day of discovery.</p>
            <p>Notwithstanding anything to the contrary, Company shall have the right collect and analyze data and any other information relating to the provision, use and performance of various aspects of the Services and related systems and technologies (including, without limitation, information concerning Customer, data and insights derived therefrom), and Company will be free (during and after the term hereof) to (i) use such information and data to improve and enhance the Services and for other development of products, diagnostic and corrective purposes in connection with the Services and other Company offerings, and (ii) disclose such data in connection with its business. No rights or licenses are granted except as expressly set forth herein.</p>

            <h4>PAYMENT OF FEES</h4>
            <p>Customer will pay Company the applicable fees, disclosed at sign-up, for the Services in accordance with the terms therein (the “Fees”). If Customer’s use of the Services requires the payment of additional fees (per the terms of this Agreement), Customer shall be charged for such usage and Customer agrees to pay the additional fees in the manner provided herein.  Company reserves the right to change the Fees or applicable charges and to institute new charges and Fees at any time, upon prior notice to Customer (which may be sent by email). If Customer believes that Company has charged Customer incorrectly, Customer must contact Company no later than 30 days after the date of the charge in which the alledged error or problem appeared, in order to be eligible receive an adjustment or credit, pending Company investigation and approval of said adjustment or credit. Inquiries should be directed to Company’s customer support.</p>
            <p>Company shall automatically charge Customer for use of Services based on the Customer’s credit card on file. The amount of the charge each month is based on the latest pricing schedule provided to the customer either on the Company website or via email. Customer agrees and consents to not receiving notification when their credit card is charged. Customer is responsible for maintaining accurate and current credit card information for the Company to charge as part of each monthly cycle. Unpaid amounts are subject to a finance charge of 1.5% per month on any outstanding balance, or the maximum permitted by law, whichever is lower, plus all expenses of collection and may result in immediate termination of Services. Customer shall be responsible for all taxes associated with Services other than U.S. taxes based on Company’s net income.</p>
            <p>Upon cancellation, no proration shall be applied to the amount Customer has paid for that term.</p>

            <h4>TERM AND TERMINATION</h4>
            <p>Subject to earlier termination as provided below, this Agreement is for the Initial Service Term as specified above, and shall be automatically renewed for additional periods of the same duration as the Initial Service Term (collectively, the “Term”), unless either party requests termination at least thirty (15) days prior to the end of the then-current term.</p>
            <p>In addition to any other remedies it may have, either party may also terminate this Agreement upon fifteen (15) days’ notice (or immediately and without notice in the case of nonpayment), if the other party materially breaches any of the terms or conditions of this Agreement. Customer will pay in full for the Services up to and including the end of the last Term in which the Services are provided. All sections of this Agreement which by their nature should survive termination will survive termination, including, without limitation, accrued rights to payment, confidentiality obligations, warranty disclaimers, and limitations of liability.</p>

            <h4>WARRANTY AND DISCLAIMER</h4>
            <p>Company shall use reasonable efforts consistent with prevailing industry standards to maintain the Services in a manner which minimizes errors and interruptions in the Services and shall perform the Services in a professional and workmanlike manner.  Services may be temporarily unavailable for scheduled maintenance or for unscheduled emergency maintenance, either by Company or by third-party providers, or because of other causes beyond Company’s reasonable control, but Company shall use reasonable efforts to provide advance notice in writing or by e-mail of any scheduled service disruption.  However, Company does not warrant that the Services will be uninterrupted or error free; nor does it make any warranty as to the results that may be obtained from use of the Services.  EXCEPT AS EXPRESSLY SET FORTH IN THIS SECTION, THE SERVICES AND IMPLEMENTATION SERVICES ARE PROVIDED “AS IS” AND COMPANY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</p>

            <h4>LIMITATION OF LIABILITY</h4>
            <p>NOTWITHSTANDING ANYTHING TO THE CONTRARY, EXCEPT FOR BODILY INJURY OF A PERSON, COMPANY AND ITS SUPPLIERS (INCLUDING BUT NOT LIMITED TO ALL EQUIPMENT AND TECHNOLOGY SUPPLIERS), OFFICERS, AFFILIATES, REPRESENTATIVES, CONTRACTORS AND EMPLOYEES SHALL NOT BE RESPONSIBLE OR LIABLE WITH RESPECT TO ANY SUBJECT MATTER OF THIS AGREEMENT OR TERMS AND CONDITIONS RELATED THERETO UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY: (A) FOR ERROR OR INTERRUPTION OF USE OR FOR LOSS OR INACCURACY OR CORRUPTION OF DATA OR COST OF PROCUREMENT OF SUBSTITUTE GOODS, SERVICES OR TECHNOLOGY OR LOSS OF BUSINESS; (B) FOR ANY INDIRECT, EXEMPLARY, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES; (C) FOR ANY MATTER BEYOND COMPANY’S REASONABLE CONTROL; OR (D) FOR ANY AMOUNTS THAT, TOGETHER WITH AMOUNTS ASSOCIATED WITH ALL OTHER CLAIMS, EXCEED THE FEES PAID BY CUSTOMER TO COMPANY FOR THE SERVICES UNDER THIS AGREEMENT IN THE ONE MONTH PRIOR TO THE ACT THAT GAVE RISE TO THE LIABILITY, IN EACH CASE, WHETHER OR NOT COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>

            <h4>MISCELLANEOUS</h4>
            <p>If any provision of this Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this Agreement will otherwise remain in full force and effect and enforceable.  This Agreement is not assignable, transferable or sublicensable by Customer except with Company’s prior written consent.  Company may transfer and assign any of its rights and obligations under this Agreement without consent.  This Agreement is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of this Agreement, and that all waivers and modifications must be in a writing signed by both parties, except as otherwise provided herein.  No agency, partnership, joint venture, or employment is created as a result of this Agreement and Customer does not have any authority of any kind to bind Company in any respect whatsoever.  In any action or proceeding to enforce rights under this Agreement, the prevailing party will be entitled to recover costs and attorneys’ fees.  All notices under this Agreement will be in writing and will be deemed to have been duly given when received, if personally delivered; when receipt is electronically confirmed, if transmitted by facsimile or e-mail; the day after it is sent, if sent for next day delivery by recognized overnight delivery service; and upon receipt, if sent by certified or registered mail, return receipt requested.  This Agreement shall be governed by the laws of the State of Illinois and any court proceedings will take place in Elgin, Illinois without regard to its conflict of laws provisions. Company may periodically contact Customer and/or Assistant Users for customer service, product management, feedback or research purposes. By accessing Services, Customer and Assistant Users consent to receive such communications. If agreed to by both parties, said parties shall work together in good faith to issue at least one mutually agreed upon testimonial within 90 days of the Effective Date and Company may reference its business relationship with Customer in its marketing or sales materials. Customer otherwise agrees to reasonably cooperate with Company to serve as a reference account upon request.</p>

            <div className="container__centertext">
                <button onClick={props.toggle} className="link-button-dark">Back</button>
            </div>

        </div>

    )
}

export default TermsPage